import {createHash} from "node:crypto";

export type TeachingV4DomainId = "teachingWorkloadDemands" | "teachingSupport" | "teachingEngagementMeaning" | "sleepRest" | "emotionalWellbeing";
export type NonTeachingV4DomainId = "nonTeachingWorkloadDemands" | "nonTeachingSupport" | "nonTeachingEngagementMeaning" | "sleepRest" | "emotionalWellbeing";
export type WorkplaceV4Direction = "risk" | "protective";
export type WorkplaceV4Item = {id: string; domainId: string; displayOrder: number; direction: WorkplaceV4Direction; constructId: string; text: string};

const item = (id: string, domainId: string, displayOrder: number, direction: WorkplaceV4Direction, constructId: string, text: string): WorkplaceV4Item => ({id, domainId, displayOrder, direction, constructId, text});

const sharedSleep = (prefix: string, order: number): WorkplaceV4Item[] => [
  item(`${prefix}_sleep_rest_01`, "sleepRest", order, "protective", "sleep_onset", "I was able to fall asleep in a reasonable amount of time."),
  item(`${prefix}_sleep_rest_02`, "sleepRest", order + 1, "risk", "sleep_continuity", "I woke during sleep and found it difficult to return to sleep."),
  item(`${prefix}_sleep_rest_03`, "sleepRest", order + 2, "protective", "sleep_rest", "I got enough sleep to feel rested the next day."),
  item(`${prefix}_sleep_rest_04`, "sleepRest", order + 3, "protective", "sleep_refreshment", "I woke feeling refreshed."),
  item(`${prefix}_sleep_rest_05`, "sleepRest", order + 4, "protective", "sleep_routine", "My sleep and wake times were close to the schedule I intended."),
  item(`${prefix}_sleep_rest_06`, "sleepRest", order + 5, "risk", "daytime_alertness", "I struggled to stay awake during the day because I had not slept enough."),
  item(`${prefix}_sleep_rest_07`, "sleepRest", order + 6, "risk", "sleep_worry", "Worrying thoughts made it hard for me to fall asleep."),
  item(`${prefix}_sleep_rest_08`, "sleepRest", order + 7, "protective", "rest_opportunity", "I had enough opportunity to rest when I needed it."),
  item(`${prefix}_sleep_rest_09`, "sleepRest", order + 8, "protective", "sleep_quality", "I was satisfied with the quality of my sleep."),
  item(`${prefix}_sleep_rest_10`, "sleepRest", order + 9, "protective", "sleep_wind_down", "I was able to set aside time to wind down before sleep."),
];
const sharedEmotional = (prefix: string, order: number): WorkplaceV4Item[] => [
  item(`${prefix}_emotional_wellbeing_01`, "emotionalWellbeing", order, "protective", "emotional_positivity", "I felt cheerful or in good spirits."),
  item(`${prefix}_emotional_wellbeing_02`, "emotionalWellbeing", order + 1, "protective", "emotional_calm", "I felt calm and settled."),
  item(`${prefix}_emotional_wellbeing_03`, "emotionalWellbeing", order + 2, "protective", "emotional_engagement", "I felt interested in my day-to-day activities."),
  item(`${prefix}_emotional_wellbeing_04`, "emotionalWellbeing", order + 3, "protective", "frustration_coping", "I felt able to handle everyday frustrations."),
  item(`${prefix}_emotional_wellbeing_05`, "emotionalWellbeing", order + 4, "protective", "emotional_awareness", "I could recognize what I was feeling."),
  item(`${prefix}_emotional_wellbeing_06`, "emotionalWellbeing", order + 5, "protective", "hope", "I felt hopeful about the near future."),
  item(`${prefix}_emotional_wellbeing_07`, "emotionalWellbeing", order + 6, "risk", "emotional_exhaustion", "I felt emotionally drained."),
  item(`${prefix}_emotional_wellbeing_08`, "emotionalWellbeing", order + 7, "risk", "emotional_demands", "I felt overwhelmed by everyday emotional demands."),
  item(`${prefix}_emotional_wellbeing_09`, "emotionalWellbeing", order + 8, "protective", "emotional_recovery", "I could regain emotional balance after an ordinary setback."),
  item(`${prefix}_emotional_wellbeing_10`, "emotionalWellbeing", order + 9, "protective", "emotional_satisfaction", "I felt satisfied with my current emotional well-being."),
];

export const TEACHING_V4_ITEMS: readonly WorkplaceV4Item[] = [
  item("teaching_v4_workload_demands_01", "teachingWorkloadDemands", 1, "protective", "workload_manageability", "My teaching workload felt manageable."), item("teaching_v4_workload_demands_02", "teachingWorkloadDemands", 2, "protective", "preparation_time", "I had enough time to prepare for my teaching responsibilities."), item("teaching_v4_workload_demands_03", "teachingWorkloadDemands", 3, "risk", "deadline_pressure", "I found it difficult to keep up with work deadlines."), item("teaching_v4_workload_demands_04", "teachingWorkloadDemands", 4, "risk", "administrative_load", "Administrative duties competed with the time I needed for teaching."), item("teaching_v4_workload_demands_05", "teachingWorkloadDemands", 5, "protective", "role_clarity", "I was clear about what was expected of me in my role."), item("teaching_v4_workload_demands_06", "teachingWorkloadDemands", 6, "protective", "prioritization", "I was able to prioritize my work responsibilities."), item("teaching_v4_workload_demands_07", "teachingWorkloadDemands", 7, "risk", "work_personal_boundary", "My work extended into time I intended for my personal life."), item("teaching_v4_workload_demands_08", "teachingWorkloadDemands", 8, "risk", "work_pace", "The pace of my teaching-related responsibilities was difficult to sustain."), item("teaching_v4_workload_demands_09", "teachingWorkloadDemands", 9, "protective", "work_control", "I had enough control over how I organized my work."), item("teaching_v4_workload_demands_10", "teachingWorkloadDemands", 10, "protective", "time_sufficiency", "I could complete my essential duties within a reasonable amount of working time."),
  item("teaching_v4_support_01", "teachingSupport", 11, "protective", "colleague_support", "I could rely on colleagues for help when I needed it."), item("teaching_v4_support_02", "teachingSupport", 12, "protective", "speaking_up_safety", "I felt safe raising a workplace concern."), item("teaching_v4_support_03", "teachingSupport", 13, "protective", "leadership_listening", "Department or unit leaders listened to concerns from staff."), item("teaching_v4_support_04", "teachingSupport", 14, "protective", "workplace_respect", "I was treated with respect at work."), item("teaching_v4_support_05", "teachingSupport", 15, "protective", "recognition", "My contributions were acknowledged."), item("teaching_v4_support_06", "teachingSupport", 16, "protective", "feedback_quality", "The feedback I received helped me improve my work."), item("teaching_v4_support_07", "teachingSupport", 17, "protective", "teaching_resources", "I had access to the resources I needed to teach effectively."), item("teaching_v4_support_08", "teachingSupport", 18, "protective", "communication_clarity", "Important workplace information was communicated clearly."), item("teaching_v4_support_09", "teachingSupport", 19, "protective", "support_navigation", "I knew where to seek help for a workplace or well-being concern."), item("teaching_v4_support_10", "teachingSupport", 20, "protective", "professional_belonging", "I felt part of a cooperative professional community."),
  item("teaching_v4_engagement_meaning_01", "teachingEngagementMeaning", 21, "protective", "work_meaning", "My teaching work felt meaningful to me."), item("teaching_v4_engagement_meaning_02", "teachingEngagementMeaning", 22, "protective", "positive_contribution", "I felt that my work made a positive contribution to students or the university."), item("teaching_v4_engagement_meaning_03", "teachingEngagementMeaning", 23, "protective", "work_interest", "I remained interested in my teaching and professional tasks."), item("teaching_v4_engagement_meaning_04", "teachingEngagementMeaning", 24, "protective", "strength_use", "I had opportunities to use my strengths in my work."), item("teaching_v4_engagement_meaning_05", "teachingEngagementMeaning", 25, "protective", "professional_growth", "I had opportunities to learn or grow professionally."), item("teaching_v4_engagement_meaning_06", "teachingEngagementMeaning", 26, "protective", "role_self_efficacy", "I felt capable of handling the challenges that came with my role."), item("teaching_v4_engagement_meaning_07", "teachingEngagementMeaning", 27, "protective", "work_autonomy", "I had enough choice in how I approached my work."), item("teaching_v4_engagement_meaning_08", "teachingEngagementMeaning", 28, "protective", "progress", "I could see progress in work that mattered to me."), item("teaching_v4_engagement_meaning_09", "teachingEngagementMeaning", 29, "protective", "work_absorption", "I experienced periods of strong focus and involvement in my work."), item("teaching_v4_engagement_meaning_10", "teachingEngagementMeaning", 30, "protective", "role_motivation", "I felt motivated to continue contributing in my professional role."),
  ...sharedSleep("teaching_v4", 31), ...sharedEmotional("teaching_v4", 41),
];

export const NON_TEACHING_V4_ITEMS: readonly WorkplaceV4Item[] = [
  item("non_teaching_v4_workload_demands_01", "nonTeachingWorkloadDemands", 1, "protective", "workload_manageability", "My workload felt manageable."), item("non_teaching_v4_workload_demands_02", "nonTeachingWorkloadDemands", 2, "protective", "time_sufficiency", "I had enough time to complete my main work duties."), item("non_teaching_v4_workload_demands_03", "nonTeachingWorkloadDemands", 3, "risk", "deadline_pressure", "I found it difficult to keep up with work deadlines."), item("non_teaching_v4_workload_demands_04", "nonTeachingWorkloadDemands", 4, "risk", "interruptions", "Frequent interruptions made it difficult to complete my work."), item("non_teaching_v4_workload_demands_05", "nonTeachingWorkloadDemands", 5, "protective", "role_clarity", "I was clear about what was expected of me in my role."), item("non_teaching_v4_workload_demands_06", "nonTeachingWorkloadDemands", 6, "risk", "work_pace", "The pace of my work was difficult to sustain."), item("non_teaching_v4_workload_demands_07", "nonTeachingWorkloadDemands", 7, "risk", "work_personal_boundary", "My work extended into time I intended for my personal life."), item("non_teaching_v4_workload_demands_08", "nonTeachingWorkloadDemands", 8, "risk", "task_load", "I found it difficult to manage several work responsibilities at the same time."), item("non_teaching_v4_workload_demands_09", "nonTeachingWorkloadDemands", 9, "protective", "prioritization", "I was able to prioritize my work responsibilities."), item("non_teaching_v4_workload_demands_10", "nonTeachingWorkloadDemands", 10, "protective", "work_completion", "I could complete my essential duties within a reasonable amount of working time."),
  item("non_teaching_v4_support_01", "nonTeachingSupport", 11, "protective", "supervisor_support", "I could ask my supervisor for help when I needed it."), item("non_teaching_v4_support_02", "nonTeachingSupport", 12, "protective", "coworker_support", "I could rely on coworkers for help when I needed it."), item("non_teaching_v4_support_03", "nonTeachingSupport", 13, "protective", "speaking_up_safety", "I felt safe raising a workplace concern."), item("non_teaching_v4_support_04", "nonTeachingSupport", 14, "protective", "workplace_respect", "I was treated with respect at work."), item("non_teaching_v4_support_05", "nonTeachingSupport", 15, "protective", "recognition", "My contributions were acknowledged."), item("non_teaching_v4_support_06", "nonTeachingSupport", 16, "protective", "supervisor_listening", "My supervisor listened when I raised a work-related concern."), item("non_teaching_v4_support_07", "nonTeachingSupport", 17, "protective", "work_resources", "I had access to the tools and resources needed for my duties."), item("non_teaching_v4_support_08", "nonTeachingSupport", 18, "protective", "communication_clarity", "Important workplace information was communicated clearly."), item("non_teaching_v4_support_09", "nonTeachingSupport", 19, "protective", "support_navigation", "I knew where to seek help for a workplace or well-being concern."), item("non_teaching_v4_support_10", "nonTeachingSupport", 20, "protective", "team_cooperation", "My team cooperated when work demands were high."),
  item("non_teaching_v4_engagement_meaning_01", "nonTeachingEngagementMeaning", 21, "protective", "work_meaning", "My work felt meaningful to me."), item("non_teaching_v4_engagement_meaning_02", "nonTeachingEngagementMeaning", 22, "protective", "positive_contribution", "I felt that my work contributed positively to the university community."), item("non_teaching_v4_engagement_meaning_03", "nonTeachingEngagementMeaning", 23, "protective", "work_interest", "I remained interested in my day-to-day work."), item("non_teaching_v4_engagement_meaning_04", "nonTeachingEngagementMeaning", 24, "protective", "strength_use", "I had opportunities to use my strengths in my work."), item("non_teaching_v4_engagement_meaning_05", "nonTeachingEngagementMeaning", 25, "protective", "skill_growth", "I had opportunities to learn or develop useful skills."), item("non_teaching_v4_engagement_meaning_06", "nonTeachingEngagementMeaning", 26, "protective", "role_self_efficacy", "I felt capable of handling the challenges that came with my role."), item("non_teaching_v4_engagement_meaning_07", "nonTeachingEngagementMeaning", 27, "protective", "work_autonomy", "I had enough choice in how I approached my work."), item("non_teaching_v4_engagement_meaning_08", "nonTeachingEngagementMeaning", 28, "protective", "progress", "I could see progress in work that mattered to me."), item("non_teaching_v4_engagement_meaning_09", "nonTeachingEngagementMeaning", 29, "protective", "work_absorption", "I experienced periods of strong focus and involvement in my work."), item("non_teaching_v4_engagement_meaning_10", "nonTeachingEngagementMeaning", 30, "protective", "role_motivation", "I felt motivated to continue contributing in my role."),
  ...sharedSleep("non_teaching_v4", 31), ...sharedEmotional("non_teaching_v4", 41),
];

export const TEACHING_V4_INSTRUMENT_VERSION = "teaching_workplace_reflection_v4";
export const NON_TEACHING_V4_INSTRUMENT_VERSION = "non_teaching_workplace_reflection_v4";
export const TEACHING_V4_ALGORITHM_VERSION = "teaching_profile_v4";
export const NON_TEACHING_V4_ALGORITHM_VERSION = "non_teaching_profile_v4";
export const TEACHING_V4_CATALOG_HASH = createHash("sha256").update(JSON.stringify(TEACHING_V4_ITEMS)).digest("hex");
export const NON_TEACHING_V4_CATALOG_HASH = createHash("sha256").update(JSON.stringify(NON_TEACHING_V4_ITEMS)).digest("hex");
export const TEACHING_V4_DOMAIN_ORDER: readonly TeachingV4DomainId[] = ["teachingWorkloadDemands", "teachingSupport", "teachingEngagementMeaning", "sleepRest", "emotionalWellbeing"];
export const NON_TEACHING_V4_DOMAIN_ORDER: readonly NonTeachingV4DomainId[] = ["nonTeachingWorkloadDemands", "nonTeachingSupport", "nonTeachingEngagementMeaning", "sleepRest", "emotionalWellbeing"];
export const TEACHING_V4_DOMAIN_LABELS: Record<TeachingV4DomainId, string> = {teachingWorkloadDemands: "Teaching Workload & Role Demands", teachingSupport: "Collegial & Organizational Support", teachingEngagementMeaning: "Professional Engagement & Meaning", sleepRest: "Sleep & Rest", emotionalWellbeing: "Emotional Well-Being"};
export const NON_TEACHING_V4_DOMAIN_LABELS: Record<NonTeachingV4DomainId, string> = {nonTeachingWorkloadDemands: "Workload & Role Demands", nonTeachingSupport: "Supervisor, Team & Organizational Support", nonTeachingEngagementMeaning: "Work Engagement & Meaning", sleepRest: "Sleep & Rest", emotionalWellbeing: "Emotional Well-Being"};
